

@baseUrl = http://localhost:8000/my_app


### Get all tasks
POST {{baseUrl}}/register/ HTTP/1.1
Content-Type: application/json

{
    "name": "Chitoge Kirisaki",
    "birth_day": "2004-01-01",
    "email": "Chitoge@gmail.com",
    "address": "123 Main St, Springfield",
    "phone_number": "123-456-7890",
    "passphrase":"12345678aA@"
}



###
POST {{baseUrl}}/login/ HTTP/1.1
Content-Type: application/json

{
    "email": "Chitoge@gmail.com",
    "passphrase":"87654321aA@"

} 

###

POST {{baseUrl}}/create_rsa_pair/ HTTP/1.1
Content-Type: application/json

{
    "user_id": 10,
    "passphrase": "87654321aA@"
}
### 
POST {{baseUrl}}/user/update/ HTTP/1.1
Content-Type: application/json

{
    "user_id": 10,
    "name": "Chitoge Kirisaki hihi",
    "current_passphrase": "87654321aA@",
    "new_passphrase": "12345678aA@"

}



###

12345678aA
87654321aA

UWMqQghaJXqZZUscXNB78A==
+v2Cyi0fR3mzhO/NQ+gPwtFARZ3sYaxHl6Ha8KrpDQ4=