

@baseUrl = http://localhost:8000/api


### Get all tasks
POST {{baseUrl}}/register/ HTTP/1.1
Content-Type: application/json

{
    "name": "hollowKnight",
    "birth_day": "2004-01-01",
    "email": "hollowKnight@gmail.com",
    "address": "123 Main St, Springfield",
    "phone_number": "123-456-7890",
    "passphrase":"12345678aA@"
}


### Login - Sinh OTP
POST {{baseUrl}}/login/ HTTP/1.1
Content-Type: application/json

{
  "email": "phhoangquan@gmail.com",
  "passphrase": "a12345678aA@"
}


### Verify OTP
POST http://localhost:8000/api/otp/verify/
Content-Type: application/json
Cookie: sessionid=wtr9pcw8y3nr2bv9v235yycxrct8412w

{
    "email": "phhoangquan@gmail.com",
    "otp": "328505"
}



###

POST {{baseUrl}}/create_rsa_pair/ HTTP/1.1
Content-Type: application/json

{
    "user_id": 	17,
    "passphrase": "12345678aA@"
}
### 
POST {{baseUrl}}/user/update/ HTTP/1.1
Content-Type: application/json

{
    "user_id": 19,
    "name": "hollowKnigh Gamer",
    "current_passphrase": "12345678aA@",
    "new_passphrase": "87654321aA@"
}
###

@file_path = "/home/akerman0509/semester_3_2025/ComputerSec/project1/my_stuff/pr1.pdf"

### 6 7 16
###
POST {{baseUrl}}/send_encrypted_file/ HTTP/1.1
Content-Type: application/json

{
    "file_path": "/home/akerman0509/semester_3_2025/ComputerSec/project1/my_stuff/img1.jpg",
    "sender_email": "phhoangquan@gmail.com",
    "recipient_email": "akerman0509@gmail.com",
    "mode": "split"
}


### 
POST {{baseUrl}}/decrypt_file/ HTTP/1.1
Content-Type: application/json

{
    "user_id":17,
    "passphrase": "12345678aA@",
    "file_path": "/home/akerman0509/semester_3_2025/ComputerSec/project1/my_stuff/img1.jpg.enc"

}


### Create QR
POST {{baseUrl}}/generate_qr/ HTTP/1.1
Content-Type: application/json

{
    "user_id": 7,
    "passphrase": "12345678aA@"
}

### Test read QR code 
POST http://127.0.0.1:8000/api/scan_qr/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="qr_image"; filename="qr_phhoangquangmail.com.png"
Content-Type: image/png

< ./applications/data/qr_codes/qr_ngthequan.relaxgmail.com.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### search public key
GET {{baseUrl}}/public_key_by_email/phhoangquan@gmail.com HTTP/1.1


###
POST {{baseUrl}}/serve_jpg/ HTTP/1.1
Content-Type: application/json

{
    "file_path": "./applications/data/qr_codes/qr_phhoangquangmail.com.png"
}

# Digital Signature

### Get Token
POST {{baseUrl}}/token/
Content-Type: application/json

{
  "email": "ngthequan.relax@gmail.com",
  "passphrase": "12345678aA@"
}

### Create signature
POST {{baseUrl}}/sign-file/ HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Token ed7f8de001a6c59261ca09321aeb05ab7510e746

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

This is a test file for digital signature.
Hello World!
Test content for signing.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="passphrase"

12345678aA@
------WebKitFormBoundary7MA4YWxkTrZu0gW--



### Verify signature
POST {{baseUrl}}/verify-signature/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Token ed7f8de001a6c59261ca09321aeb05ab7510e746

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="original_file"; filename="test.txt"
Content-Type: text/plain

This is a test file for digital signature.
Hello World!
Test content for signing.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="signature_file"; filename="test.sig"
Content-Type: application/octet-stream

{
  "file_name": "test.txt",
  "file_hash": "8492ca20ed0c9d673ca814acbdb5cb41b22ea59750cb382173f83a28e4944f94",
  "signature": "Akn7jx7kKIfg5OEmsJ0SmwTd0qMeECXdjuFtnRvGBZLs/FKB387VOhWh0QxTlflv2Fxr6y2GKYmF3SMpHVESOWqPg4UsRXDEaFJeuM26BMOVqzWFxLDj/zcQwaTZPX01iIxyWd+OUupj4vbcbhogbO3suhQBQyPTCDlQWY9LZPQ8Z4Bj3xy0zfvrlYm8UaMVRStnTE5UsvvqZVrK4gT1A3KA2AAYubznz1hretwgil4Mlt2F03GlVBAEt0TdAodTdPcd1JcQuBfXrwFvCEprFuOEiNhLTvte0dGHnNeo7xS27s/E3vak+ISJpUHa+WB6uw1M6yZjsakRQgX8ZsZYyA==",
  "signer_email": "ngthequan.relax@gmail.com",
  "signer_name": "ngthequan.relax@gmail.com",
  "signed_at": "2025-07-10T07:36:19.590210+00:00",
  "algorithm": "RSA-PSS with SHA-256"
}
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#############------ADMIN-----------###############
POST {{baseUrl}}/register/ HTTP/1.1
Content-Type: application/json

{
    "name": "Admin User",
    "birth_day": "2004-01-01",
    "email": "akerman0509@gmail.com",
    "address": "123 Main St, Springfield",
    "phone_number": "123-456-7890",
    "passphrase":"12345678aA@", 
    "role": "ADMIN"
}

### Get all account

GET {{baseUrl}}/my_admin/17/list_account/ HTTP/1.1

### block/unblock account
POST {{baseUrl}}/my_admin/17/change_account_status/ HTTP/1.1
Content-Type: application/json

{
    "target_id":19,
    "new_status": "BLOCKED" 
}
### BLOCKED / ACTIVE


### Encrypt large file
POST {{baseUrl}}/encrypt-large-file/ HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

ngthequan.relax@gmail.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="5MB.pdf"
Content-Type: application/octet-stream

< /home/ngthequan/Documents/Project1/computer_sec_pr1/applications/data/EncryptLargeFile/Upload/5MB.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Check key status
GET {{baseUrl}}/key-status/ngthequan.relax@gmail.com/ HTTP/1.1 Content-Type: application/json

### Renew key
POST {{baseUrl}}/renew-key/ HTTP/1.1 
Content-Type: application/json

{ "email": "ngthequan.relax@gmail.com", "passphrase": "12345678aA@" }
